### ISSUE TITLE
"TypeError: The "listener" argument must be of type Function. Received type object" when using with NextJS

### ISSUE THREAD

**Issue by MindSetFPS** [Yimura/Scraper#14] opened 2022-04-17 22:07 UTC
After a clean installation of NextJS and calling the scraper in index,js following the documentation, it will throw the error "TypeError: The "listener" argument must be of type Function. Received type object".

Running the scraper from a file in the terminal runs as expected.

Node Version: 14.19.1
NPM Version: 6.14.16

1. Install NextJS
2. Install Scraper
3. Call scraper in Index.js

Doing logging the result in index,js apparently works, but the frontend will be broken.

**Comment by Yimura** [comment] 2022-04-17 22:18
Interesting, could you give some code indicating how you import the scraper and set it up? (as I'm not familiar with NextJS)
```js
// just putting this here as an example
import scraper from '@yimura/scraper'

const yt = new scraper.default();
```

This module should work as long as it runs server side in a Node environment, if the code is somehow being transformed to be usable on browser then it won't work unless making changes to the actual codebase.

**Comment by GeopJr** [comment] 2022-04-18 23:50
Reproduction + fix: https://stackblitz.com/edit/nextjs-uktyyb?file=pages/index.js (will most likely only work on chromium based browsers)

The main idea is to run it server-side only by wrapping it in an if statement that checks if it's client side

```js
const yt = new youtube.default();
let rickroll = '';
if (typeof window === 'undefined') {
  console.log('SCRAPER IS RUNNING!');
  yt.search('Never gonna give you up').then((results) => {
    rickroll = results.videos[0]?.link;
  });
}
```

This will obviously run only when server-side gets executed (like when `npm run dev` runs, but not when it rerenders).

```
SCRAPER IS RUNNING!
error - unhandledRejection: TypeError: Failed to fetch
error - unhandledRejection: Error: socket hang up
```

(errors related to scraper, probably due to stackblitz or other)

Error on client-side is probably related to `https`. Over at unjs, there's [ohmyfetch](https://github.com/unjs/ohmyfetch) which works seamlessly between node and browser, however it's up to Yimura to decide whether introducing a dependency is worth it.

After all Scraper's main goal was to be "A Youtube Scraper **with zero dependencies.** " 

edit:
Maybe a separate `scraper-browser` package?

or just a `scraper-browser.js` that uses browser apis instead of https?

**Comment by Yimura** [comment] 2022-04-22 10:42
@MindSetFPS I will close the issue now, if you have further questions about this specific issue continue commenting below here, I will reopen it if needed.

**Closed as completed by Yimura** 2022-04-22 10:42 UTC
Labels: question
